In [37]:
import pandas as pd
import numpy as np

import nltk
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline

from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB 

from sklearn.multiclass import OneVsRestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

from scipy.sparse import csr_matrix
from scipy.sparse import hstack

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
# Display setting to show more characters
pd.options.display.max_colwidth = 100
pd.options.display.max_rows = 100

In [3]:
df = pd.read_csv("C:/Users/User/OneDrive - Singapore Management University/YALING SMU MITB/10 APPLIED MACHINE LEARNING/Project/Latest Consolidated/sampdf_feat.csv") 

In [4]:
df.shape

(54870, 19)

In [27]:
df.head(100)

id  \
0   3bf7c95e20e164f1   
1   8dfbb26d7edb4e39   
2   ec8eb2974a3b7686   
3   587075cbd150aee1   
4   d8d76d16e8369ff8   
5   80769e4a460902ae   
6   33809f03610f4306   
7   6d59909aa7f48bcc   
8   d9a3ebd0fa5c5ff4   
9   9e3084b3ee4ff605   
10  15285cfa9ec7f36d   
11  19ff6cc1e08ff469   
12  d94c86e30da4e008   
13  13c18eb9bd828cf5   
14  8f664f4b5bda385e   
15  7c8c921afa499ef7   
16  c5d79f9bd7f70b0f   
17  ec1b117bc313943f   
18  db2f01d32abd6859   
19  21bbdfc834d1e9c0   
20  204e2a16adb6e024   
21  1ed5dab581e48905   
22  cfbd8225fcf6088b   
23  d88550cbce7e34a7   
24  1ac6632114db603d   
25  3f0ebb3da83212a5   
26  f20b1a6c0d890a68   
27  d3363825f335b731   
28  baf42febc98d3ff0   
29  83f7610ddf39f857   
30  1ee672c68e42edce   
31  d1dc51b86232dd36   
32  11d1c619bcbf4f05   
33  ea01a7ad234acfa5   
34  8526678c815ec295   
35  1081c0c626dc3248   
36  6ba38cbf591fc331   
37  ecad882627ecb95f   
38  09e8c02643395198   
39  ad751eafc56798b3   
40  4d12ae07eccd3b73   
41  310c5ad2668e5e33   
42  be5bcaa9cf5e22fb   
43  f8253747287dd963   
44  70d25fc76ff79b76   
45  3bb8a4cf506d45c1   
46  8efb7be6057ba9a9   
47  75e48bc64a59c4bf   
48  934a86c13fca1d43   
49  707f2bbc0ac1080d   
50  f1cc79a202953be5   
51  c55565345e94829b   
52  42ef5e37ba37b936   
53  22445ac5fc94f7bd   
54  b9615a0385018eb6   
55  a39beb70743f701a   
56  22d33bd3bb8415cb   
57  514d25ad0cf970e4   
58  306d4c3ea0cd0f1c   
59  fc2de51c75913c20   
60  9a8f0e725204383d   
61  60a5ff5e275f4b8f   
62  86638219e8cad5e0   
63  3603bc46289b4810   
64  c348687d23cc9c94   
65  33927ffe27ddea5f   
66  6f29485b79869886   
67  a985bbd53663441d   
68  fb9861d011ac4459   
69  79ce6b00fd504dab   
70  31100e3308d6732a   
71  384ef27c1bac0e77   
72  5e89d90d43f1c8e0   
73  fa45ff15ec85272b   
74  ba40d806c7a63849   
75  ccc8f45c0b367173   
76  cdb85bb3678fe3d1   
77  d045b8733b3254b0   
78  b700b18d1639c7a7   
79  9dd622cddfa0918f   
80  cfdec8c3d25f6a26   
81  1c390518ab61e6db   
82  58d79a0a860e0d7b   
83  6852122d14074afc   
84  7efb71f381b0d429   
85  8c4b0ba8737d89c8   
86  7e64acfc89f2ffe8   
87  b2be1be3e1acf344   
88  6005f1547a8e62b7   
89  c6b38704ab555153   
90  0b65658f6826ff9e   
91  dfa7cf98ef39b4af   
92  fdb2f27d0fa6d222   
93  6b782bffc72722fd   
94  cfd0286fb534a1c9   
95  a8c148310c2a3a8b   
96  9783766755ab36a7   
97  466b3f40ad4ab719   
98  64d733e7a27bf5dd   
99  90a30c58086e6ba3   

                                                                                           comment_text  \
0   you do interesting work! \n\nReally, whatever the outcome on Aetherometry, all the best with you...   
1   Let me see if I understand you. Because the site is run by religious, nationalistic Iranians, it...   
2                                       Yes, I will try to cut out the details to make it more compact.   
3                       timestamp to unsigned templates, so you do it for me. Thanks! )   t c 03:08, 25   
4   I replaced the quote as to my count three contributers seem to have been happy with the quote, i...   
5   " \n\n  \n == Cookies! == \n Spam is mystery meat.  Let's have cookies!  \n\n   has given you a ...   
6                                                               "\nEmail. —  • Talk •  "   
7   GAR\nThanks for the heads-up. Looking over the nomination, I agree with the rationales listed so...   
8   "\nThe vandalism was coming from autoconfirmed users, the pages had been semi-protected ages ago...   
9                                          " \n\n ::Good point, I fixed that. —  •  •  "   
10  the green cup \n\n  \n hello young viewers i would like to inform you about the story of the gre...   
11  """Of course, this isn’t the first time Leinart has proven to be clueless about the NFL. A ...   
12                 No, current events are pretty important for this newsmaker.  Just my view  legacypac   
13  " 2007 (UTC)\n\nHi.  1.) I must've mistakenly thought Ian was an original member b/c he's a

In [6]:
# subset the dataframe
df1 = df.iloc[:,[0,9,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18]]

In [7]:
df1.head()

id  \
0  3bf7c95e20e164f1   
1  8dfbb26d7edb4e39   
2  ec8eb2974a3b7686   
3  587075cbd150aee1   
4  d8d76d16e8369ff8   

                                                                                                                                                                                                cleaned_comment_text  \
0                                                                                                        interest work ! Really whatever outcome Aetherometry best wheelchair work That look like fascinate engineer   
1                                                                        Let see I understand you Because site run religious nationalistic Iranians must steal content This must bizarro world logic I familiar with   
2                                                                                                                                                                                  Yes I try cut detail make compact   
3                                                                                                                                                                         timestamp unsigned templates me Thanks ! c   
4  I replace quote count three contributers seem happy quote i e consensus within term page It may idea anything contentious article address issue surround trouble fully reference everything accord wiki standards   

   toxic  severe_toxic  obscene  threat  insult  identity_hate  clean  \
0      0             0        0       0       0              0      1   
1      0             0        0       0       0              0      1   
2      0             0        0       0       0              0      1   
3      0             0        0       0       0              0      1   
4      0             0        0       0       0              0      1   

   word_count  char_count  word_density  total_length  capitals  \
0          15          93      0.159574           107         3   
1          22         118      0.184874           139         6   
2           7          27      0.250000            33         2   
3           7          36      0.189189            42         1   
4          31         179      0.172222           209         2   

   caps_vs_length  num_exclamation_marks  num_unique_words  words_vs_unique  
0        0.028037                      1                14         0.933333  
1        0.043165                      0                20         0.909091  
2        0.060606                      0                 7         1.000000  
3        0.023810                      1                 7         1.000000  
4        0.009569                      0                30         0.967742

### Train / Test Split

In [8]:
# create train and test set (note that x and y are not separated due to nltk's way of feature selection)
train, test = train_test_split(df1, test_size = 0.2, random_state = 2019)

In [9]:
train.shape

(43896, 18)

In [10]:
train.head()

id  \
6902   737becdcbbdb26e0   
38124  95610e068ba8cef7   
18589  31d601c5e57ec545   
51305  6f4c12e0b10c4400   
30972  4feee2e51847c96c   

                                                                                                                                                                                                                                                                                                                                                                                                                     cleaned_comment_text  \
6902                                                                                                                                                                                                                                                                                                                                                                                  It certainly refer distinction find within language   
38124                                                                                                                                                                                                                                                                                                                                                                                              Listen fuckers dont come say shit face   
18589                                                                                                                                                                                                                                                                                                                                                                                       Building encyclopedia Glad back Take care fun   
51305                                                                                                                                                                                                                                                                                                                                                                                       Awesome Quote Not idiots boys boys idiots ! !   
30972  The term Bathroom use basically apply room actually bath or alternatively shower both it For toilet call list things toilet dunny John shithouse commode essentially name except bathroom Curse word generally same although couple soften blow Bugger still rude notably less rude word For full list Australian slang check page lot things help But since Steve Irwin normal Australian use word Crikey Thanks link Fantastic !   

       toxic  severe_toxic  obscene  threat  insult  identity_hate  clean  \
6902       0             0        0       0       0              0      1   
38124      1             1        1       0       1              0      0   
18589      0             0        0       0       0              0      1   
51305      1             0        1       0       1              0      0   
30972      0             0        0       0       0              0      1   

       word_count  char_count  word_density  total_length  capitals  \
6902            7          45      0.152174            51         1   
38124           7          32      0.212121            38         1   
18589           7          39      0.175000            45         3   
51305           9          37      0.236842            45         3   
30972          66         353      0.186441           418        15   

       caps_vs_length  num_exclamation_marks  num_unique_words  \
6902         0.019608                      0                 7   
38124        0.026316                      0                 7   
18589        0.066667                      0                 7   
51305        0.066667                      2                 6   
30972        0.035885                      1                57 

In [11]:
test.shape

(10974, 18)

In [12]:
test.head()

id  \
18383  c18844370ce4a022   
27385  25b14fc6b4548258   
20223  e04e436acbee81bc   
13495  5abeb566790f299e   
3693   9ce29fbc9129e190   

                                                                                                                                                                                                                                                                                                                                                                           cleaned_comment_text  \
18383                                                                                                                                                                                                                                                                                                                        sound excat tide fat roll guy must guy jeez fuck wikapeida commies   
27385  Hi I flatter ask take look though article something I absolutely knowledge ! On first read seem well write article appropriate reference support claim The comment I express date term BP Before Present rather term BC even BCE I confess I never see BP before ! As possible tautology I convince It appear me read well enough be I would certainly encourage crack Hope use ! Cheers   
20223                                                                                                                                                                                                                                                                              Sure thingthanks make look twice As MagicView say I mean much better much appropriate tone I admire patience   
13495                                                                                                                                                                                                                                                                                                                                          re Gates What diff go make talk technical reason   
3693                                                                                                                                                                                                                                           Oppose per Vegaswikian I never hear book hear plenty people give name There also Ian McKellen film call Emile really legitimate reason make move   

       toxic  severe_toxic  obscene  threat  insult  identity_hate  clean  \
18383      0             0        0       0       0              0      1   
27385      0             0        0       0       0              0      1   
20223      0             0        0       0       0              0      1   
13495      0             0        0       0       0              0      1   
3693       0             0        0       0       0              0      1   

       word_count  char_count  word_density  total_length  capitals  \
18383          12          55      0.214286            66         0   
27385          67         310      0.215434           376        25   
20223          18          91      0.195652           108         6   
13495           9          40      0.219512            48         2   
3693           24         121      0.196721           144         8   

       caps_vs_length  num_exclamation_marks  num_unique_words  \
18383        0.000000                      0                11   
27385        0.066489                      3                54   
20223        0.055556                      0                16   
13495        0.041667                      0                 9   
3693         0.055556                      0                23   

       words_vs_unique  
18383         0.916667  
27385         0.805970  
20223         0.888889  
13495         1.000000  
3693          0.958333

### feature engineering

In [13]:
def extract_label_features(df, label, flag, topwords):
    
    # extract comments from label==flag (1 or 0)
    a = df[df[label]==flag].values.tolist()
    
    # combine comments into a single list
    b = [item[1] for item in a]
    
    # word tokenize each comment
    c = [word_tokenize(i) for i in b]
    
    # remove additional stopwords and words with 2 characters
    stop_list = ['wikipedia', 'wiki']
    d = [[w for w in doc if w not in stop_list and len(w)>2] for doc in c]
   
    # convert nested list into a single list
    e = [w for doc in d for w in doc]
    
    # frequency distribution of words
    f = nltk.FreqDist(e)
    print(len(f))
    
    # create word features using only top most common words in all documents
    word_features = [item[0] for item in f.most_common(topwords)]
    
    return word_features

In [14]:
toxic1 = extract_label_features(train, 'toxic', 1, 3000)
print(toxic1)

40316
['YOU', 'fuck', 'You', 'FUCK', 'you', 'like', 'THE', 'DIE', 'shit', 'get', 'NIGGER', 'SUCK', 'faggot', 'ass', 'know', 'page', 'suck', 'edit', 'make', 'article', 'hate', 'people', 'nigger', 'stupid', 'Fuck', 'gay', 'SHIT', 'The', 'say', 'think', 'FAT', 'one', 'bitch', 'BITCH', 'would', 'Wikipedia', 'AND', 'block', 'want', 'JEW', 'ARE', 'DICKS', 'FAGGOT', 'talk', 'ALL', 'GAY', 'CUNT', 'time', 'HATE', 'YOUR', 'yourself', 'sex', 'FUCKING', 'little', 'see', 'Bark', 'WIKIPEDIA', 'What', 'penis', 'take', 'And', 'use', 'This', 'cock', 'delete', 'even', 'need', 'BALLS', 'AIDS', 'THIS', 'give', 'stop', 'life', 'asshole', 'try', 'tell', 'call', 'Why', 'really', 'right', 'come', 'love', 'DICK', 'cunt', 'WANKER', 'ANAL', 'Nipple', 'dick', 'Your', 'look', 'guy', 'name', 'dickhead', 'mother', 'CAN', 'good', 'vandalism', 'way', 'write', 'back', 'piece', 'mean', 'bastard', 'MUST', 'idiot', 'fucksex', 'yourselfgo', 'work', 'KILL', 'admin', 'User', 'moron', 'ban', 'ASS', 'rule', 'hell', 'remove', '

In [51]:
toxic0 = extract_label_features(train, 'toxic', 0, 1000)
print(toxic0)

69584
['article', 'page', 'The', 'edit', 'Wikipedia', 'would', 'use', 'make', 'one', 'talk', 'like', 'think', 'say', 'source', 'You', 'see', 'know', 'get', 'add', 'time', 'people', 'This', 'Please', 'also', 'need', 'name', 'link', 'find', 'want', 'you', 'work', 'take', 'may', 'remove', 'delete', 'block', 'look', 'write', 'change', 'please', 'could', 'information', 'comment', 'section', 'even', 'list', 'point', 'Thanks', 'way', 'give', 'try', 'mean', 'help', 'good', 'seem', 'read', 'image', 'question', 'deletion', 'first', 'much', 'not', 'well', 'reference', 'revert', 'ask', 'right', 'And', 'here', 'include', 'reason', 'discussion', 'really', 'come', 'this', 'place', 'create', 'Talk', 'many', 'call', 'word', 'that', 'tag', 'Thank', 'issue', 'There', 'post', 'state', 'back', 'That', 'new', 'user', 'leave', 'mention', 'two', 'someone', 'case', 'show', 'put', 'fact', 'still', 'claim', 'something', 'What', 'consider', 'content', 'without', 'since', 'note', 'But', 'believe', 'might', 'intere

In [52]:
# combine word features of both labels
word_features = toxic1 + toxic0

In [53]:
# Define function for feature extraction
def document_features(document):
    document_words1 = word_tokenize(document)
    document_words2 = set(document_words1)
    features = {}
    for word in word_features:
        features['contains(%s)' % word] = (word in document_words2)
    return features

### 1st level classifer - word features only

In [54]:
# transform train features into vectors
train1 = train.values.tolist()
train2 = [item[1] for item in train1]
train_feature = [document_features(i) for i in train2]
v = DictVectorizer()
train_feature1 = v.fit_transform(train_feature)

In [55]:
# transform test features into vectors
test1 = test.values.tolist()
test2 = [item[1] for item in test1]
test_feature = [document_features(i) for i in test2]
test_feature1 = v.transform(test_feature) 

In [56]:
binary_pipeline = Pipeline([('clf', MultinomialNB()),])

categories = ['toxic']

for category in categories:
    
    print('... Processing {}'.format(category))
    
    # train the model
    binary_pipeline.fit(train_feature1, train[category])
    
    # compute the testing accuracy
    y_pred = binary_pipeline.predict(test_feature1)
    
    # evaluate performance   
    print('\nConfusion matrix:\n', confusion_matrix(test[category], y_pred))
    print('\nAccuracy: {}%'.format(round(100*accuracy_score(test[category], y_pred),2)))
    print('\nClasification report:\n', classification_report(test[category], y_pred))
    
    precision, recall, f1_score, support = precision_recall_fscore_support(test[category], y_pred, beta=1, average='weighted')
    print(precision, recall, f1_score, support)

... Processing toxic

Confusion matrix:
 [[5909  820]
 [ 549 3696]]

Accuracy: 87.53%

Clasification report:
               precision    recall  f1-score   support

           0       0.91      0.88      0.90      6729
           1       0.82      0.87      0.84      4245

    accuracy                           0.88     10974
   macro avg       0.87      0.87      0.87     10974
weighted avg       0.88      0.88      0.88     10974

0.8776352583946352 0.8752505923090942 0.8758981664686128 None


### 2nd level model training

In [61]:
subdf = df1[df1['toxic']==1]
subdf.shape

(21383, 18)

In [62]:
# create train and test set (note that x and y are not separated due to nltk's way of feature selection)
toxic1train, toxic1test = train_test_split(subdf, test_size = 0.2, random_state = 2019)

In [63]:
toxic1train.shape

(17106, 18)

In [64]:
toxic1test.shape

(4277, 18)

In [65]:
toxic1_severe1 = extract_label_features(toxic1train, 'severe_toxic', 1, 600)
print(toxic1_severe1)

7318
['YOU', 'FUCK', 'fuck', 'SUCK', 'THE', 'suck', 'bitch', 'faggot', 'FUCKING', 'yourself', 'You', 'you', 'AND', 'DIE', 'YOUR', 'shit', 'BITCH', 'fucksex', 'yourselfgo', 'ALL', 'ARE', 'NIGGER', 'FAGGOT', 'cock', 'MUST', 'ass', 'CUNT', 'WIKIPEDIA', 'Fuck', 'like', 'nigger', 'gay', 'NIGGERJEW', 'HUGE', 'KILL', 'eat', 'FUK', 'TRAITOR', 'VANDAL', 'bastard', 'DAMN', 'penis', 'WILL', 'THIS', 'DOG', 'RAPE', 'SHUT', 'OFFFUCK', 'MEXICANS', 'piece', 'HanibalYou', 'Pro', 'Assad', 'ANAL', 'stupid', 'SHIT', 'asshole', 'NIGGERS', 'pussy', 'FUCKER', 'MOTHERFUCKERDIE', 'CriminalWar', 'BunkSteve', 'COCKSUCKER', 'MOTHJER', 'Chester', 'DICK', 'MarcolFuck', 'little', 'Small', 'GAY', 'CAN', 'FAT', 'dick', 'FACK', 'Notrhbysouthbanof', 'USELESS', 'BLOCK', 'BOT', 'veggietales', 'love', 'get', 'FAGS', 'want', 'COCKSUCKING', 'Fucking', 'mother', 'SUCKS', 'ASSHOLE', 'moron', 'whore', 'fat', 'edit', 'shitFuck', 'Anthony', 'Bradbury', 'ATHEIST', 'GOD', 'die', 'YOURSELF', 'BALLZ', 'kid', 'CUNTS', 'FIRED', 'kill',

In [66]:
toxic1_obscene1 = extract_label_features(toxic1train, 'obscene', 1, 1000)
print(toxic1_obscene1)

25270
['YOU', 'fuck', 'FUCK', 'You', 'THE', 'suck', 'you', 'shit', 'SUCK', 'NIGGER', 'bitch', 'like', 'AND', 'FUCKING', 'Fuck', 'get', 'penis', 'ass', 'CUNT', 'BITCH', 'know', 'ARE', 'stupid', 'page', 'NIGGERS', 'yourself', 'edit', 'FAT', 'YOUR', 'faggot', 'make', 'cock', 'article', 'asshole', 'people', 'ALL', 'DIE', 'Nipple', 'gay', 'nigger', 'think', 'DICK', 'say', 'FAGGOT', 'The', 'want', 'block', 'hate', 'dick', 'GAY', 'JEW', 'youfuck', 'fucksex', 'yourselfgo', 'little', 'one', 'bastard', 'would', 'FREEDOM', 'take', 'Wikipedia', 'piece', 'love', 'talk', 'THIS', 'YOUFUCK', 'WIKIPEDIA', 'cunt', 'delete', 'BUTTSECKS', 'eat', 'time', 'SHIT', 'ASS', 'FUK', 'poop', 'VANDAL', 'MUST', 'fat', 'life', 'TRAITOR', 'give', 'see', 'CAN', 'HUGE', 'mother', 'NIGGERJEW', 'What', 'SHUT', 'This', 'guy', 'DAMN', 'DICKS', 'pussy', 'fag', 'big', 'SUCKS', 'Why', 'And', 'use', 'Assad', 'tell', 'Hey', 'even', 'RAPE', 'stop', 'dickhead', 'DOG', 'Pro', 'FUCKER', 'need', 'OFFFUCK', 'MEXICANS', 'HanibalYou', '

In [67]:
toxic1_threat1 = extract_label_features(toxic1train, 'threat', 1, 600)
print(toxic1_threat1)

3436
['YOU', 'DIE', 'THE', 'MUST', 'KILL', 'WILL', 'you', 'VANDAL', 'TRAITOR', 'FUK', 'kill', 'AND', 'YOUR', 'You', 'fuck', 'YOURSELF', 'JIM', 'WALES', 'ALL', 'WIKIPEDIA', 'BAN', 'NIGGGERS', 'murder', 'die', 'BLOCK', 'ball', 'get', 'LIFETIME', 'rip', 'decapitate', 'tiny', 'shit', 'FUCK', 'TALK', 'bitch', 'PAGE', 'RVV', 'BLANK', 'FUCKING', 'ass', 'BURN', 'GET', 'FUCKIN', 'like', 'LIFE', 'CUT', 'HELL', 'hope', 'SuPeRTRLL', 'WiLL', 'know', 'one', 'CONTINUE', 'life', 'YOUCALTLAS', 'come', 'OUT', 'CORPSE', 'LOSER', 'would', 'see', 'fat', 'time', 'think', 'page', 'Fuck', 'delete', 'little', 'make', 'edit', 'say', 'HATE', 'Die', 'unblock', 'AGAIN', 'CHILDREN', 'block', 'find', 'want', 'need', 'death', 'SHOOT', 'MOTHER', 'BLAAAM', 'dead', 'cunt', 'gon', 'ASS', 'GON', 'TAKE', 'WANTA', 'BAIL', 'BEAVIS', 'BUTTHEAD', 'JESSICA', 'SIMPSON', 'shoot', 'stupid', 'hell', 'RAPE', 'THEIR', 'NIGGAZ', 'MOONSHINE', 'DUST', 'FILTER', 'live', 'piece', 'MURDER', 'ORGANS', 'STEAL', 'PASSWORD', 'OVER', 'people', 

In [68]:
toxic1_insult1 = extract_label_features(toxic1train, 'insult', 1, 1000)
print(toxic1_insult1)

23677
['YOU', 'fuck', 'FUCK', 'You', 'NIGGER', 'suck', 'SUCK', 'bitch', 'shit', 'you', 'like', 'THE', 'FAT', 'faggot', 'AND', 'FUCKING', 'JEW', 'stupid', 'get', 'know', 'BITCH', 'ARE', 'ass', 'NIGGERS', 'Fuck', 'gay', 'yourself', 'page', 'YOUR', 'edit', 'CUNT', 'make', 'people', 'asshole', 'ALL', 'nigger', 'DIE', 'HATE', 'hate', 'think', 'FAGGOT', 'GAY', 'article', 'DICK', 'block', 'youfuck', 'yourselfgo', 'little', 'want', 'cock', 'say', 'one', 'FREEDOM', 'penis', 'bastard', 'would', 'piece', 'THIS', 'Please', 'YOUFUCK', 'The', 'Wikipedia', 'delete', 'moron', 'VANDAL', 'life', 'ASS', 'dick', 'idiot', 'cunt', 'fat', 'take', 'FUK', 'SHIT', 'MUST', 'time', 'TRAITOR', 'eat', 'HUGE', 'NIGGERJEW', 'retard', 'fag', 'willy', 'talk', 'admin', 'guy', 'DAMN', 'Nigga', 'mother', 'love', 'Why', 'see', 'dickhead', 'Hey', 'DOG', 'Your', 'What', 'stop', 'pussy', 'give', 'FUCKER', 'MEXICANS', 'And', 'Pro', 'Assad', 'big', 'HanibalYou', 'This', 'need', 'even', 'use', 'die', 'SUCKS', 'call', 'work', 'TH

In [69]:
toxic1_identity1 = extract_label_features(toxic1train, 'identity_hate', 1, 600)
print(toxic1_identity1)

8434
['NIGGER', 'FAT', 'JEW', 'gay', 'NIGGERS', 'fuck', 'GAY', 'nigger', 'AND', 'You', 'FAGGOT', 'SUCK', 'faggot', 'FUCK', 'YOU', 'FUCKING', 'NIGGERJEW', 'HUGE', 'Please', 'stupid', 'suck', 'like', 'Nigga', 'THE', 'MEXICANS', 'shit', 'bitch', 'ass', 'CUNT', 'BunkSteve', 'FRANCE', 'Nigger', 'TOMMY', 'get', 'FAGS', 'TURKEYFUCK', 'make', 'nigga', 'faggotgay', 'licker', 'Fan', 'BALLZ', 'ALL', 'TURKEY', 'fag', 'die', 'HATE', 'you', 'know', 'people', 'eat', 'KILL', 'night', 'Fuck', 'dick', 'YOUR', 'PIECE', 'homo', 'NIGGGERS', 'ASS', 'THIS', 'would', 'think', 'little', 'last', 'SHIT', 'page', 'AIDS', 'User', 'UTC', 'life', 'say', 'love', 'alert', 'cody', 'article', 'want', 'one', 'ARE', 'mitt', 'romney', 'Cline', 'The', 'white', 'JEWS', 'block', 'SPICS', 'MINORITIES', 'shitty', 'cunt', 'right', 'edit', 'CHINK', 'JForget', 'COCKSUCKING', 'fat', 'HOMO', 'kill', 'FUCKIN', 'them', 'benon', 'retard', 'guy', 'Your', 'black', 'need', 'Get', 'NACONKANTARI', 'LOLOLOLOL', 'AMERICAN', 'take', 'CALVIN', 

In [70]:
# combine word features of all labels
word_features = toxic1_severe1 + toxic1_obscene1 + toxic1_threat1 + toxic1_insult1 + toxic1_identity1

In [71]:
# Define function for feature extraction
def document_features(document):
    document_words1 = word_tokenize(document)
    document_words2 = set(document_words1)
    features = {}
    for word in word_features:
        features['contains(%s)' % word] = (word in document_words2)
    return features

### 2nd level classifier

In [72]:
toxic1train2 = toxic1train.values.tolist()
toxic1train3 = [item[1] for item in toxic1train2]

toxic1test2 = toxic1test.values.tolist()
toxic1test3 = [item[1] for item in toxic1test2]

# loop through documents list and create feature set list
train_feature = [document_features(i) for i in toxic1train3]
test_feature = [document_features(i) for i in toxic1test3]

In [73]:
# transform nltk features into vectors
v = DictVectorizer()

train_feature1 = v.fit_transform(train_feature)

test_feature1 = v.transform(test_feature) 

In [74]:
multilabel_pipeline = Pipeline([('clf', OneVsRestClassifier(MultinomialNB())),])

categories = ['severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

for category in categories:
    
    print('... Processing {}'.format(category))
    
    # train the model
    multilabel_pipeline.fit(train_feature1, toxic1train[category])
    
    # compute the testing accuracy
    y_pred = multilabel_pipeline.predict(test_feature1)
    
    # evaluate performance   
    print('\nConfusion matrix:\n', confusion_matrix(toxic1test[category], y_pred))
    print('\nAccuracy: {}%'.format(round(100*accuracy_score(toxic1test[category], y_pred),2)))
    print('\nClasification report:\n', classification_report(toxic1test[category], y_pred))

... Processing severe_toxic

Confusion matrix:
 [[3520  361]
 [ 217  179]]

Accuracy: 86.49%

Clasification report:
               precision    recall  f1-score   support

           0       0.94      0.91      0.92      3881
           1       0.33      0.45      0.38       396

    accuracy                           0.86      4277
   macro avg       0.64      0.68      0.65      4277
weighted avg       0.89      0.86      0.87      4277

... Processing obscene

Confusion matrix:
 [[1351  670]
 [ 438 1818]]

Accuracy: 74.09%

Clasification report:
               precision    recall  f1-score   support

           0       0.76      0.67      0.71      2021
           1       0.73      0.81      0.77      2256

    accuracy                           0.74      4277
   macro avg       0.74      0.74      0.74      4277
weighted avg       0.74      0.74      0.74      4277

... Processing threat

Confusion matrix:
 [[4009  151]
 [  66   51]]

Accuracy: 94.93%

Clasification report:
       

In [76]:
multilabel_pipeline = Pipeline([('clf', OneVsRestClassifier(MultinomialNB())),])

categories = ['severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# train the model
multilabel_pipeline.fit(train_feature1, toxic1train[categories])

# compute the testing accuracy
y_pred = multilabel_pipeline.predict(test_feature1)

# evaluate performance   
#print('\nAccuracy: {}%'.format(round(100*accuracy_score(toxic1test[categories], y_pred),2)))
#print('\nPrecision: {}%'.format(round(100*precision_score(toxic1test[categories], y_pred, average='micro'),2)))
#print('\nRecall: {}%'.format(round(100*recall_score(toxic1test[categories], y_pred, average='micro'),2)))
#print('\nf1-score: {}%'.format(round(100*f1_score(toxic1test[categories], y_pred, average='micro'),2)))

In [77]:
y_pred.shape

(4277, 5)

In [78]:
no_of_labels = 5

In [79]:
toxic1test.iloc[:,3:8]

severe_toxic  obscene  threat  insult  identity_hate
47295             0        0       0       1              1
34487             0        0       0       1              0
49587             0        1       0       0              0
52905             0        1       0       1              0
34082             0        0       0       0              0
...             ...      ...     ...     ...            ...
36004             0        0       0       0              0
40598             0        0       0       1              0
37516             0        1       0       1              0
45595             0        1       0       1              0
52744             0        1       0       0              0

[4277 rows x 5 columns]

In [80]:
toxic1test.iloc[:,3:8].values

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       ...,
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0]], dtype=int64)

In [81]:
y_true = toxic1test.iloc[:,3:8].values

In [82]:
y_true

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       ...,
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0]], dtype=int64)

In [83]:
y_true.shape

(4277, 5)

In [84]:
# confusion matrix
mcm = multilabel_confusion_matrix(y_true, y_pred)
print(mcm)

[[[3520  361]
  [ 217  179]]

 [[1351  670]
  [ 438 1818]]

 [[4009  151]
  [  66   51]]

 [[1350  809]
  [ 554 1564]]

 [[3666  228]
  [ 193  190]]]


In [85]:
# TP, FP, FN, TN

TP = list()
FP = list()
FN = list()
TN = list()

for i in range(no_of_labels):
    TN_i = mcm[i][0][0]
    FP_i = mcm[i][0][1]
    FN_i = mcm[i][1][0]
    TP_i = mcm[i][1][1]
    
    TP.append(TP_i)
    FP.append(FP_i)
    FN.append(FN_i)
    TN.append(TN_i)
    
print(TP)
print(FP)
print(FN)
print(TN)

# e.g. TP for label 0 ==> TP[0]

[179, 1818, 51, 1564, 190]
[361, 670, 151, 809, 228]
[217, 438, 66, 554, 193]
[3520, 1351, 4009, 1350, 3666]


In [86]:
# accuracy

accuracy = list()
for i in range(no_of_labels):
    accuracy_i = (TP[i] + TN[i]) / (TP[i] + FP[i] + FN[i] + TN[i])
    accuracy.append(accuracy_i)

print(accuracy)

[0.8648585457096095, 0.7409399111526771, 0.9492635024549918, 0.6813186813186813, 0.9015665185877951]


In [87]:
# precision, recall, f1 score

precision = list()
recall = list()
f1_score = list()

for i in range(no_of_labels):
    precision_i = (TP[i]) / ((TP[i] + FP[i]) or not (TP[i] + FP[i]))
    precision.append(precision_i)
    
    recall_i = (TP[i]) / ((TP[i] + FN[i]) or not (TP[i] + FN[i]))
    recall.append(recall_i)
    
    f1_score_i = (2 * precision_i * recall_i) / ((precision_i + recall_i) or not (precision_i + recall_i))
    f1_score.append(f1_score_i)
    
print(precision)
print(recall)
print(f1_score)

[0.3314814814814815, 0.7307073954983923, 0.2524752475247525, 0.6590813316477033, 0.45454545454545453]
[0.45202020202020204, 0.8058510638297872, 0.4358974358974359, 0.7384324834749764, 0.4960835509138381]
[0.3824786324786325, 0.7664418212478921, 0.31974921630094044, 0.6965041193498108, 0.47440699126092384]


In [88]:
# average accuracy

avg_accuracy = sum(accuracy) / no_of_labels
print(avg_accuracy)

0.827589431844751


In [89]:
# micro averaging

micro_precision = sum(TP) / (sum(TP) + sum(FP))
micro_recall = sum(TP) / (sum(TP) + sum(FN))
micro_f1_score = (2 * micro_precision * micro_recall) / (micro_precision + micro_recall)

print(micro_precision)
print(micro_recall)
print(micro_f1_score)

0.6314565686762996
0.7214421252371916
0.6734567354530157
